server:
  port: 8888
  servlet:
    context-path: /wx_contact


spring:
    datasource:
      url: jdbc:mysql://47.110.32.211:3306/wx_contacts?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
      username: root
      password: admin_password!
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      driverClassName: com.mysql.jdbc.Driver
##############jpa配置 ##################
    jpa:
      show-sql: true #显示sql语句
      database: mysql
      hibernate:
#        naming:
#        physicalstrategy: org.hibernate.cfg.ImprovedNamingStrategy #命名策略 遇到大写字母 加”_”的命名。
#        strategy: org.hibernate.cfg.ImprovedNamingStrategy #  无修改命名
#          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # 实体类大小写不变成下划线
        ddl-auto: none
mybatis:
  mapper-locations: classpath:mapper/*.xml

##############redis配置 ##################
redis:
  host: 47.110.32.211
  port: 6379
  password: GERSDHSDFGSJY232FAS232ASH7878BNXZ323JFT;
  timeout: 10
  poolMaxTotal: 5
  poolMaxIdle: 10
  poolMaxWait: 10
  database: 3

wx:
  appId: wx983a55bf3422f686 #小程序唯一标识
  appSecret: 6c44db2ae375f58c97324958f66300eb #小程序的 app secret
  grantType: authorization_code # 授权（必填）
  userUrl: https://api.weixin.qq.com/sns/jscode2session? #小程序官方api 获取用户信息
#小程序配置信息
  miniapp:
    configs:
        appid: xxxxx
        secret: xxxxx
        token: xxxxxx
        aesKey: xxxxxx
        msgDataFormat: JSON
